todo/urls.py
from django.urls import path

from todo.views import (
    index,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    toggle_task_completion,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tag/", TagListView.as_view(), name="tags-list"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "task/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "task/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task/toggle-completion/<int:pk>",
        toggle_task_completion,
        name="toggle-task-completion",
    ),
]

app_name = "todo"

todo_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self) -> str:
        return f"{self.name}"


class Task(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["completed", "created"]

    def __str__(self) -> str:
        return f"{self.content}"

todo/forms.py
from django import forms

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    deadline = forms.DateField(widget=forms.SelectDateWidget, required=False)
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


def index(request):
    tasks = Task.objects.all()

    context = {
        "tasks": tasks,
    }

    return render(request, "todo/index.html", context)


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tags-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tags-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tags-list")


class TaskCreateView(generic.CreateView):
    form_class = TaskForm
    model = Task
    success_url = reverse_lazy("todo:index")


class TaskUpdateView(generic.UpdateView):
    form_class = TaskForm
    model = Task
    success_url = reverse_lazy("todo:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")


def toggle_task_completion(request, pk):
    task = Task.objects.get(pk=pk)
    task.completed = not task.completed
    task.save()

    return HttpResponseRedirect(reverse_lazy("todo:index"))

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>
    {% block title %}
      Todo list
    {% endblock %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>
<body>
<div class="container-fluid">
    <div class="row ms-1 mt-4 me-4">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item text-decoration-none"><a href="{% url 'todo:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tags-list' %}">Tags</a></li>
</ul>

templates/todo/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary float-end">Add task</a>
  </h1>
  <br>
  {% for task in tasks %}
    <h5>
      {{ task.content }}

      {% if task.completed %}
        <span class="text-success">Done</span>
        {% else %}
        <span class="text-danger">Not done</span>
      {% endif %}

      {% if task.completed %}
        <a href="{% url 'todo:toggle-task-completion' pk=task.id %}" class="btn btn-secondary float-end">Undo</a>
      {% else %}
        <a href="{% url 'todo:toggle-task-completion' pk=task.id %}" class="btn btn-success float-end">Complete</a>
      {% endif %}


    </h5>
    <div>
      Created: {{ task.created }}
      {% if task.deadline %}
        <span class="text-danger">Deadline: {{ task.deadline }}</span>
      {% endif %}
    </div>
    <div class="text-secondary">
      Tags:
      {% for tag in task.tags.all %}
      {{ tag.name }}
      {% endfor %}

      <a href="{% url 'todo:task-update' pk=task.id %}" class="text-decoration-none">Update</a>
      <a href="{% url 'todo:task-delete' pk=task.id %}" class="text-decoration-none">Delete</a>
    </div>
    <hr>
  {% endfor %}

{% endblock %}

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete this tag ({{ tag.name }})?</h1>

  <form action="" method="post">
    {% csrf_token %}
    <div class="ms-3">
      <input type="submit" value="Yes, I am sure" class="btn btn-success rounded-2 custom_button_delete_confirm">
      <a href="{% url 'todo:tags-list' %}" class="btn btn-danger rounded-2 ms-2 pt-1 custom_button_delete_confirm">Cancel</a>
    </div>

  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <hr>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags:
    <a href="{% url 'todo:tag-create' %}" class="btn btn-primary float-end">Add</a>
  </h1>
  <hr>

    <table class="table">

      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>

      {% for tag in tag_list %}
      <tbody>
        <tr>
          <td>{{ tag.name }}</td>
          <td><a href="{% url 'todo:tag-update' pk=tag.id %}" class="btn btn-secondary">Update</a></td>
          <td><a href="{% url 'todo:tag-delete' pk=tag.id %}" class="btn btn-secondary">Delete</a></td>
      </tbody>
      {% endfor %}
    </table>

{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete this task?</h1>

  <form action="" method="post">
    {% csrf_token %}
    <div class="ms-3">
      <input type="submit" value="Yes, I am sure" class="btn btn-success rounded-2 custom_button_delete_confirm">
      <a href="{% url 'todo:index' %}" class="btn btn-danger rounded-2 ms-2 pt-1 custom_button_delete_confirm">Cancel</a>
    </div>

  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <hr>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}